const ActionTypes = {
    /** NAMESPACE */
    USER_CONNECTION_REQUEST : 'USER_CONNECTION_REQUEST',
    USER_CONNECTION_SUCCESS : 'USER_CONNECTION_SUCESS',
    USER_CONNECTION_FAILURE : 'USER_CONNECTION_FAILURE',

    USER_DISCONNECT: 'USER_DISCONNECT',

    APP_INITIALIZED:'APP_INITIALIZED',

    BULK_DATA_REQUEST: 'BULK_DATA_REQUEST',

    INCIDENT_DATA_REQUEST: 'INCIDENT_DATA_REQUEST',

    SALES_DATA_REQUEST: 'SALES_DATA_REQUEST',

    STOCK_DATA_REQUEST: 'STOCK_DATA_REQUEST',

    PRODUCT_DATA_REQUEST: 'PRODUCT_DATA_REQUEST'

}

export default Object.freeze(ActionTypes);